version: '3.9'

services:
  db:
    image: ankane/pgvector
    restart: always
    container_name: database_vector
    ports:
      - "5444:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
    env_file:
      - ./backend/.env
    environment:
      - OPENBLAS_NUM_THREADS=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata: