version: '3.8'

services:
  db:
    #image: postgres:14
    image: pgvector/pgvector:0.7.3-pg14
    env_file:
      - .env
    environment:
      # эти переменные возьмутся из вашего .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
     # - ./init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    env_file:
      - .env
    volumes:
     - ./:/app
    # network_mode: host
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
volumes:
  pgdata:
